### PR TITLE
fix!: `to_gbq` loads `unit8` columns to BigQuery INT64 instead of STRING

### LINKED ISSUE #452: pyarrow.lib.ArrowTypeError: Expected bytes, got a 'dict' object
Hi!
there is a problem when trying to load using pandas-gbq which using pyarrow a column of the list (array) or dictionary (json) type into the table, while the GBQ documentation says that structure types such as array or json are supported,

```
df = pd.DataFrame(
                {
                    "my_string": ["a", "b", "c"],
                    "my_int64": [1, 2, 3],
                    "my_float64": [4.0, 5.0, 6.0],
                    "my_bool1": [True, False, True],
                    "my_bool2": [False, True, False],
                    "my_struct": [{"test":"str1"},{"test":"str2"},{"test":"str3"}],
                }
            )
pandas_gbq.to_gbq(df, **gbq_params)
```

as a result, a stacktrace error occurs:

- in bq_to_arrow_array
- return pyarrow.Array.from_pandas(series, type=arrow_type)
- File "pyarrow/array.pxi", line 913, in pyarrow.lib.Array.from_pandas
- File "pyarrow/array.pxi", line 311, in pyarrow.lib.array
- File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
- File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
- pyarrow.lib.ArrowTypeError: Expected bytes, got a 'dict' object

Can anyone help with it please?

### PR DESCRIPTION
**Pull request by tswast**
fix!: `to_gbq` loads `unit8` columns to BigQuery INT64 instead of STRING (#814)

fix!: `to_gbq` loads naive (no timezone) columns to BigQuery DATETIME instead of TIMESTAMP (#814)
fix!: `to_gbq` loads object column containing bool values to BOOLEAN instead of STRING (#814)
fix!: `to_gbq` loads object column containing dictionary values to STRUCT instead of STRING (#814)
deps: min pyarrow is now 4.0.0 to support compliant nested types (#814)
Release-As: 0.24.0

Note to Googlers, this copies some pandas -> BigQuery logic from both https://github.com/googleapis/python-bigquery and https://github.com/googleapis/python-bigquery-dataframes as part of an effort to reduce redundancy across code bases. My intention is to make those packages depend on pandas-gbq for pandas -> BigQuery logic.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-pandas/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #452, #105, #616, #450
🦕

### CODE REVIEW

**Comment by tswast** [comment]
```
_________________ ERROR collecting tests/system/test_to_gbq.py _________________
[tests/system/test_to_gbq.py:392](https://cs.corp.google.com/piper///depot/google3/tests/system/test_to_gbq.py?l=392): in <module>
    dtype=pandas.ArrowDtype(
[.nox/system-3-8/lib/python3.8/site-packages/pandas/__init__.py:258](https://cs.corp.google.com/piper///depot/google3/.nox/system-3-8/lib/python3.8/site-packages/pandas/__init__.py?l=258): in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
E   AttributeError: module 'pandas' has no attribute 'ArrowDtype'
```

Looks like I need to update the tests to be compatible with older pandas.

**Comment by tswast** [comment]
@Linchin @chelsea-lin please take a look. I got it working on Python 3.8 by upgrading the minimum pyarrow version from 3.0.0 (January 2021) to 4.0.0 (April 2021).

**Review by chelsea-lin — APPROVED** [review]
LGTM

File: tests/unit/schema/test_pandas_to_bigquery.py [hunk 1]
```diff
@@ -0,0 +1,156 @@
+# Copyright (c) 2019 pandas-gbq Authors All rights reserved.
```
[the remark this answers is not in the document]
Comment (tswast) [reply tests/unit/schema/test_pandas_to_bigquery.py:1]: This contains some code I copied from a file dated to 2019, so I don't think I should update this.
